### ISSUE TITLE
about DoDoCode

### ISSUE THREAD

**Issue by koki-39** [kuper-adrian/TurnipExchange#1]
I'm curious why I input ddcode to know about my island information.
Can you tell me how it's done.
I want to do a similar function in wechat app for Chinese players.
They can visit strange islands.

**Comment by kuper-adrian** [comment]
I'm not sure if I fully understand your question. In order to create a sale on the web page you have to enter your dodo code, which you can get in-game from Dodo. Tell him to open the airport gates and select the "via Dodo code" option.

This webpage only gives you the option to display the code in order to share it with other players.

**Comment by koki-39** [comment]
Yes, I got the DoDocode from the game. I requested turnip-exchange. com/offer/create this url and it will return my island's name and character name.
How do you know my island's name and character name through this dodocode. Is Nintendo there to provide the relevant API?
In other words, how do I verify that this dodocode is real?

**Comment by kuper-adrian** [comment]
Are you sure, that you are not mistaking https://turnip-exchange.com (this repo) with the unrelated page https://turnip.exchange/?

https://turnip-exchange.com (and therefore the code in this repo) is unable to retrieve the villager and island name from the dodo code. And, unlike https://turnip.exchange/ apperantly, I don't know any way to verify whether dodo codes are real or not (I only make sure that the code has a length of 5 characters).

From the FAQ of https://turnip.exchange/:
**How did it know my name and island name?**
We've been at this game for a while, so we have some special connections to help make this sort of thing work.

You may have better luck by asking in their official Discord channel: http://discord.warp.world/

**Comment by koki-39** [comment]
I'm so sorry, I made a mistake. I thought Nintendo had an open interface to look up relevant information。
Thank you very much for your answer.

**Comment by kuper-adrian** [comment]
No need to apologize 😅 Good luck on your project 👍
